name: Node.js Package
on:
  push:
    branches: [ trunk ]
jobs:
  build:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    
  # Run Slack Notification
    - name: Slack Notification
      if: always() # Pick up events even if the job fails or is canceled.
      uses: 8398a7/action-slack@v3
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
      with:
        status: ${{ job.status }}
        author_name: GitHubAction CI for NPM publish status
        mention: 'here'
        if_mention: failure,cancelled
        job_name: npm-publish # Match the name above.
        fields: repo,commit,eventName,ref,workflow,message,author,job,took
        custom_payload: |
          {
          username: 'GitHub Action CI WorkFlow',
          icon_emoji: ':github:',
          attachments: [{
            color: '${{ job.status }}' === 'success' ? 'good' : ${{ job.status }}' === 'failure' ? 'danger' : 'warning',
            text:
            `${process.env.AS_REPO}\n
            ${process.env.AS_COMMIT}\n 
            ${process.env.AS_EVENT_NAME}\n
            @${process.env.AS_REF}\n
            @${process.env.AS_WORKFLOW}\n
            ${process.env.AS_MESSAGE}\n
            ${process.env.AS_AUTHOR}\n
            ${process.env.AS_JOB}\n
            ${process.env.AS_TOOK}`,
          }]
          }